[package]
name = "efferve"
version = "0.1.0"
authors = ["shockham <samuel.hockham@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
infuse = "0.1.0"
wasm-bindgen = "0.2.43"
